### ISSUE TITLE
Race condition when building project in parallel mode

### ISSUE THREAD

**Issue by Cinek28** [phoenix-rtos/phoenix-rtos-build#18]
When using parallel building options (-j) there is a slight chance that the build will fail. As of now the build system does not take into consideration dependencies order so the build can issue errors when dependency build is not finished before the code that uses it. It is especially seen in automated build. 

The issue can be reproduced by adding delay in Makefile of one of the dependencies. For example in phoenix-rtos-devices/usb/common/Makefile add "sleep 2" to "all" target rule. The build will then fail with error: 

usb/imx-usbc/../common/usbclient.h:19:10: fatal error: usb.h: No such file or directory

**Comment by pawelpisarczyk** [comment]
Marcin, It seems that it is due to incorrect Makefile structure in usb/common. Please ask Hubert to check this.

**Comment by nalajcie** [comment]
should be fixed now.
