### ISSUE TITLE
clang-format badly formats switch statement

### ISSUE THREAD

**Issue by kemonats** [phoenix-rtos/phoenix-rtos-build#53]
I think this line should be added to the `.clang-format` file:
```
IndentCaseLabels: 'false'
```
Snippet of code from [imxrt117x-cm4.c](https://github.com/phoenix-rtos/phoenix-rtos-devices/blob/master/cpu/imxrt117x-cm4/imxrt117x-cm4.c):
```c
	switch (i->type) {
	case m4_loadBuff:
		if (msg->i.data == NULL || msg->i.size == 0) {
			o->err = -EINVAL;
			break;
		}

		o->err = loadFromBuff(msg->i.data, msg->i.size);
		break;

	case m4_loadFile:
		if (msg->i.data == NULL || msg->i.size == 0) {
			o->err = -EINVAL;
			break;
		}

		o->err = loadFromFile(msg->i.data);
		break;

	case m4_runCore:
		o->err = runCore();
		break;

	default:
		o->err = -EINVAL;
		break;
	}
```
After using clang-format:
```c
	switch (i->type) {
		case m4_loadBuff:
			if (msg->i.data == NULL || msg->i.size == 0) {
				o->err = -EINVAL;
				break;
			}

			o->err = loadFromBuff(msg->i.data, msg->i.size);
			break;

		case m4_loadFile:
			if (msg->i.data == NULL || msg->i.size == 0) {
				o->err = -EINVAL;
				break;
			}

			o->err = loadFromFile(msg->i.data);
			break;

		case m4_runCore:
			o->err = runCore();
			break;

		default:
			o->err = -EINVAL;
			break;
	}
```
With the above-mentoined line of the `.clang-format` file added, the code is not reformatted.

**Comment by nalajcie** [comment]
As I see it - we're using both styles in existing code (even in kernel - simple `grep -R -A2 switch` shows that :)). 

I think we should decide on one syntax and reformat existing code, @agkaminski which syntax is correct according to our coding style? If it's not clearly defined, we should update the coding standard and then reformat the code.

**Comment by nalajcie** [comment]
@agkaminski, @anglov - what do You think?

**Comment by agkaminski** [comment]
@nalajcie Yes, this isn't clearly defined by our rules and it's a matter of taste, but it should be unified in all code.

I am leaning towards not idented (first example) style of switch-case.

@pawelpisarczyk do you have a preference on this matter?

**Comment by anglov** [comment]
Well, we talk about it with @agkaminski recently and I believe this is undefined in our code style and, as you told, both styles exist in current code.

Honestly I prefer the indented one but it's my personal preference. Coding style rule need to be defined and then applied.

**Comment by agkaminski** [comment]
We've picked indented style in the end
